spring:
  datasource:
    url:
    username:
    password:
  application:
    name: Spring Boot Demo
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    show-sql: true
  devtools:
    restart:
      enabled: true
logging:
  level:
    org.springframework: trace