spring:
  datasource:
    url: jdbc:mysql://rm-2zef51knj3983di49uo.mysql.rds.aliyuncs.com:3306/demo?useUnicode=true&characterEncoding=utf8&autoReconnect=true&jdbcCompliantTruncation=false&zeroDateTimeBehavior=convertToNull
    username: qyb_ysjs_test
    password: gzzhy2020@2603
  application:
    name: Spring Boot Demo
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    show-sql: true
  devtools:
    restart:
      enabled: true